# Generated by Django 2.0.5 on 2018-05-25 13:52

from django.db import migrations


def create_tasks_and_users(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Task = apps.get_model("app", "Task")
    for num in range(100000):
        task = Task(title=f'task#{num}')
        task.save()
    User = apps.get_model("app", "User")
    for num in range(10000):
        user = User(username=f'user#{num}', password=f'mgtu1234{num}', first_name=f'name#{num}')
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_tasks_and_users)
    ]
